<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\BG.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/3D-web/3dmodels/BG.glb')
</script>

{#if $gltf}
<T.Group 
  position={[-35,-2, 45]}
  rotation={[0, (Math.PI / 2) + 0.5, 0]}
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={329.69}>
      <T.Mesh
        geometry={gltf.nodes.Plane010.geometry}
        material={gltf.materials['grass floor']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_1.geometry}
        material={gltf.materials.floor}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_2.geometry}
        material={gltf.materials.street}
      />
    </T.Group>
    <T.Group
      position={[33, 1.24, 67]}
      rotation={[Math.PI / 2, 0, -2.23]}
      scale={1.24}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane009.geometry}
        material={gltf.materials.car}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane009_1.geometry}
        material={gltf.materials['dress red']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane009_2.geometry}
        material={gltf.materials.ram}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane009_3.geometry}
        material={gltf.materials['blue tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane009_4.geometry}
        material={gltf.materials['center flower']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.rock.geometry}
      material={gltf.materials.rock}
      position={[45.53, 0, 35.97]}
      scale={[0.8, 0.41, 0.8]}
    />
    <T.Mesh
      geometry={gltf.nodes.grass008.geometry}
      material={gltf.materials.grass}
      position={[34.07, 0, 41.07]}
      scale={0.52}
    />
    <T.Mesh
      geometry={gltf.nodes.grass012.geometry}
      material={gltf.materials.grass}
      position={[16.53, 0, 72.64]}
      scale={0.52}
    />
    <T.Group
      position={[9.03, 0, 75.1]}
      scale={0.41}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane181.geometry}
        material={gltf.materials['center flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane181_1.geometry}
        material={gltf.materials['leafs flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane181_2.geometry}
        material={gltf.materials['roots flower']}
      />
    </T.Group>
    <T.Group
      position={[38.46, 0, 56.97]}
      scale={0.41}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane194.geometry}
        material={gltf.materials['center flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane194_1.geometry}
        material={gltf.materials['leafs flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane194_2.geometry}
        material={gltf.materials['roots flower']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 36]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane081.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane081_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane081_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 42]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane082.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane082_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane082_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 48]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane083.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane083_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane083_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 54]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane084.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane084_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane084_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 60]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane085.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane085_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane085_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 66]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane086.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane086_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane086_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 72]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane087.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane087_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane087_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 78]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane088.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane088_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane088_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[53, 0, 84]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane089.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane089_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane089_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[28, -0.44, 82.98]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane131.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane131_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane131_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[22, -0.33, 82.99]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane132.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane132_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane132_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[16, -0.22, 82.99]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane133.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane133_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane133_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[10, -0.11, 83]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane134.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane134_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane134_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[46, -0.05, 84]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane141.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane141_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane141_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[40, 0.05, 84]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane142.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane142_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane142_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
    <T.Group
      position={[34, 0.16, 84.01]}
      rotation={[-1.53, -1.55, -1.57]}
      scale={[0.35, 0.4, 0.35]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane143.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane143_1.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane143_2.geometry}
        material={gltf.materials['dark leafes tree']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
{/if}
