<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\computer.glb
Author: crusadjor (https://sketchfab.com/crusadjor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-voxel-retro-computer-d93b923c8e284281891203bf4362e83c
Title: Free Voxel Retro Computer | Ретро Компьютер
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('3dmodels/computer.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
      <T.Group position={[-20, -15, -8]}>
        <T.Mesh
          geometry={gltf.nodes.Object_5.geometry}
          material={gltf.materials.VoxMaterial_2}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_6.geometry}
          material={gltf.materials.VoxMaterial_3}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_7.geometry}
          material={gltf.materials.VoxMaterial_213}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_8.geometry}
          material={gltf.materials.VoxMaterial_243}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_9.geometry}
          material={gltf.materials.VoxMaterial_248}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_10.geometry}
          material={gltf.materials.VoxMaterial_249}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_11.geometry}
          material={gltf.materials.VoxMaterial_250}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_12.geometry}
          material={gltf.materials.VoxMaterial_253}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_13.geometry}
          material={gltf.materials.VoxMaterial_254}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
