<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/scene.gltf -u -s -k
Author: HansWurschd (https://sketchfab.com/HansWurschd)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lego-space-dart-i-2fc7d4ad36ed451d8cb5256de50d4b28
Title: LEGO Space Dart I
-->

<script>
	import { base } from '$app/paths';
  import { T } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const suspend = useSuspense()

  const gltf = suspend(useGltf(base+'/models/scene.gltf'))
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="Sketchfab_model"
      rotation={[-Math.PI / 2, 0, 0]}
    >
      <T.Group
        name="Collada_visual_scene_group"
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          name="23-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material'].geometry}
          material={gltf.materials.material_5}
          position={[-4.28, 46.61, 8.19]}
          rotation={[-0.1, -0.07, 0.57]}
        />
        <T.Mesh
          name="23-material_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_1'].geometry}
          material={gltf.materials.material_5}
          position={[-6.41, 46.24, -4]}
          rotation={[-0.33, -0.2, 0.54]}
        />
        <T.Mesh
          name="23-material_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_2'].geometry}
          material={gltf.materials.material_5}
          position={[-18.5, 34.44, 6.2]}
          rotation={[0.39, 0.08, 0.2]}
        />
        <T.Mesh
          name="23-material_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_3'].geometry}
          material={gltf.materials.material_5}
          position={[-17.99, 41.45, -4]}
          rotation={[0.13, 0.03, 0.21]}
        />
        <T.Mesh
          name="233814d130-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['233814d130-material'].geometry}
          material={gltf.materials['233814d130']}
          position={[-8.76, 35.54, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="23-material_4"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_4'].geometry}
          material={gltf.materials.material_5}
          position={[-3.23, 32.64, -4]}
          rotation={[-Math.PI / 2, -Math.PI / 8, 0]}
        />
        <T.Mesh
          name="23-material_5"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_5'].geometry}
          material={gltf.materials.material_5}
          position={[-8.76, 35.54, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="23-material_6"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_6'].geometry}
          material={gltf.materials.material_5}
          position={[-10.62, 29.57, -4]}
          rotation={[-Math.PI / 2, -Math.PI / 8, 0]}
        />
        <T.Mesh
          name="26-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material'].geometry}
          material={gltf.materials.material}
          position={[-12.66, 44.95, 14.02]}
          rotation={[-0.89, -0.31, 0.24]}
        />
        <T.Mesh
          name="2-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material'].geometry}
          material={gltf.materials.material_1}
          position={[-7.96, 33.6, 12]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="26-material_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_1'].geometry}
          material={gltf.materials.material}
          position={[-5.51, 48.54, 7.91]}
          rotation={[0.41, -0.7, 0.77]}
        />
        <T.Mesh
          name="23-material_7"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_7'].geometry}
          material={gltf.materials.material_5}
          position={[-17.87, 57.53, -4]}
          rotation={[0.37, -0.71, 0.53]}
        />
        <T.Mesh
          name="243626d154-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['243626d154-material'].geometry}
          material={gltf.materials['243626d154']}
          position={[-14.19, 48.66, -4]}
          rotation={[0.37, -0.71, 0.53]}
        />
        <T.Mesh
          name="23-material_8"
          castShadow
          receiveShadow
          geometry={gltf.nodes['23-material_8'].geometry}
          material={gltf.materials.material_5}
          position={[-13.66, 47.37, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_1'].geometry}
          material={gltf.materials.material_1}
          position={[-23.76, 19.48, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_2'].geometry}
          material={gltf.materials.material_1}
          position={[13.2, 34.79, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="44-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['44-material'].geometry}
          material={gltf.materials.material_4}
          position={[-53.83, 6.37, 7.1]}
          rotation={[Math.PI / 2, -1.18, 0]}
        />
        <T.Mesh
          name="44-material_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes['44-material_1'].geometry}
          material={gltf.materials.material_4}
          position={[43.73, 46.78, 7.1]}
          rotation={[-Math.PI / 2, 1.18, Math.PI]}
        />
        <T.Mesh
          name="41-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['41-material'].geometry}
          material={gltf.materials.material_3}
          position={[43.73, 46.78, -18.5]}
          rotation={[-Math.PI / 2, 1.18, Math.PI]}
        />
        <T.Mesh
          name="41-material_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes['41-material_1'].geometry}
          material={gltf.materials.material_3}
          position={[-53.83, 6.37, -21.7]}
          rotation={[Math.PI / 2, -1.18, 0]}
        />
        <T.Mesh
          name="26-material_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_2'].geometry}
          material={gltf.materials.material}
          position={[-53.83, 6.37, -18.5]}
          rotation={[Math.PI / 2, -1.18, 0]}
        />
        <T.Mesh
          name="26-material_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_3'].geometry}
          material={gltf.materials.material}
          position={[43.73, 46.78, -15.3]}
          rotation={[-Math.PI / 2, 1.18, Math.PI]}
        />
        <T.Mesh
          name="26-material_4"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_4'].geometry}
          material={gltf.materials.material}
          position={[-46.44, 9.43, 0]}
          rotation={[Math.PI, 0, 1.18]}
        />
        <T.Mesh
          name="26-material_5"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_5'].geometry}
          material={gltf.materials.material}
          position={[36.34, 43.72, 0]}
          rotation={[-Math.PI, 0, -1.96]}
        />
        <T.Mesh
          name="41-material_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes['41-material_2'].geometry}
          material={gltf.materials.material_3}
          position={[-6.5, 30.09, 54.4]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="2-material_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_3'].geometry}
          material={gltf.materials.material_1}
          position={[-6.5, 30.09, 35.2]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="26-material_6"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_6'].geometry}
          material={gltf.materials.material}
          position={[-6.5, 30.09, 25.6]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="2-material_4"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_4'].geometry}
          material={gltf.materials.material_1}
          position={[-6.5, 30.09, 16]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="2-material_5"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_5'].geometry}
          material={gltf.materials.material_1}
          position={[-6.5, 30.09, 16]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="41-material_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes['41-material_3'].geometry}
          material={gltf.materials.material_3}
          position={[-8.57, 35.08, -48]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="26-material_7"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_7'].geometry}
          material={gltf.materials.material}
          position={[-8.57, 35.08, -38.4]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="2-material_6"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_6'].geometry}
          material={gltf.materials.material_1}
          position={[-4.28, 24.73, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_7"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_7'].geometry}
          material={gltf.materials.material_1}
          position={[-4.28, 24.73, 12]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_8"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_8'].geometry}
          material={gltf.materials.material_1}
          position={[-19.04, 29.01, -4]}
          rotation={[Math.PI / 2, -1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_9"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_9'].geometry}
          material={gltf.materials.material_1}
          position={[3.13, 38.19, -4]}
          rotation={[-Math.PI / 2, 1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="41-material_4"
          castShadow
          receiveShadow
          geometry={gltf.nodes['41-material_4'].geometry}
          material={gltf.materials.material_3}
          position={[6.8, 29.32, 16]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="41-material_5"
          castShadow
          receiveShadow
          geometry={gltf.nodes['41-material_5'].geometry}
          material={gltf.materials.material_3}
          position={[-15.37, 20.14, 16]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="26-material_8"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_8'].geometry}
          material={gltf.materials.material}
          position={[-14.57, 18.2, -15.8]}
          rotation={[-Math.PI, 0, 2.75]}
        />
        <T.Mesh
          name="26-material_9"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_9'].geometry}
          material={gltf.materials.material}
          position={[7.61, 27.38, -15.8]}
          rotation={[-Math.PI, 0, 2.75]}
        />
        <T.Mesh
          name="48-material"
          castShadow
          receiveShadow
          geometry={gltf.nodes['48-material'].geometry}
          material={gltf.materials.material_2}
          position={[-17.51, 25.31, -1.6]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="48-material_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes['48-material_1'].geometry}
          material={gltf.materials.material_2}
          position={[4.66, 34.5, -1.6]}
          rotation={[Math.PI / 2, Math.PI / 8, 0]}
        />
        <T.Mesh
          name="2-material_10"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_10'].geometry}
          material={gltf.materials.material_1}
          position={[6.8, 29.32, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_11"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_11'].geometry}
          material={gltf.materials.material_1}
          position={[-15.37, 20.14, -4]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_12"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_12'].geometry}
          material={gltf.materials.material_1}
          position={[14.19, 32.38, 0]}
          rotation={[-Math.PI / 2, 1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_13"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_13'].geometry}
          material={gltf.materials.material_1}
          position={[-22.76, 17.08, 0]}
          rotation={[Math.PI / 2, -1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_14"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_14'].geometry}
          material={gltf.materials.material_1}
          position={[-20.31, 11.16, 0]}
          rotation={[Math.PI / 2, -1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_15"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_15'].geometry}
          material={gltf.materials.material_1}
          position={[16.64, 26.47, 0]}
          rotation={[-Math.PI / 2, 1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_16"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_16'].geometry}
          material={gltf.materials.material_1}
          position={[-3.06, 21.77, 0]}
          rotation={[-Math.PI, 0, 2.75]}
        />
        <T.Mesh
          name="2-material_17"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_17'].geometry}
          material={gltf.materials.material_1}
          position={[-1.83, 18.82, 12]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="2-material_18"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_18'].geometry}
          material={gltf.materials.material_1}
          position={[-1.83, 18.82, -12]}
          rotation={[-Math.PI, 0, 2.75]}
        />
        <T.Mesh
          name="2-material_19"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_19'].geometry}
          material={gltf.materials.material_1}
          position={[10.48, 20.45, 0]}
          rotation={[-Math.PI / 2, 1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_20"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_20'].geometry}
          material={gltf.materials.material_1}
          position={[-11.7, 11.27, 0]}
          rotation={[Math.PI / 2, -1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="2-material_21"
          castShadow
          receiveShadow
          geometry={gltf.nodes['2-material_21'].geometry}
          material={gltf.materials.material_1}
          position={[-1.83, 18.82, 0]}
          rotation={[Math.PI / 2, -1.18, Math.PI / 2]}
        />
        <T.Mesh
          name="26-material_10"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_10'].geometry}
          material={gltf.materials.material}
          position={[6.78, 18.92, 0]}
          rotation={[0, 0, Math.PI / 8]}
        />
        <T.Mesh
          name="26-material_11"
          castShadow
          receiveShadow
          geometry={gltf.nodes['26-material_11'].geometry}
          material={gltf.materials.material}
          position={[-8, 12.8, 0]}
          rotation={[0, 0, Math.PI / 8]}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
