<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 .\PixelWorld.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('3dmodels/PixelWorld.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[1, 7.46, -71]}
      rotation={[0, Math.PI / 2, 0]}
      scale={[4.96, 3.38, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube024.geometry}
        material={gltf.materials.billboards}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube024_1.geometry}
        material={gltf.materials['pr 1']}
      />
    </T.Group>
    <T.Group
      position={[37.69, 6.62, 9.1]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[4.96, 3.38, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube001.geometry}
        material={gltf.materials.billboards}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_1.geometry}
        material={gltf.materials['pr 1.002']}
      />
    </T.Group>
    <T.Group
      position={[-72.58, 6.62, 26.72]}
      rotation={[0, Math.PI / 2, 0]}
      scale={[4.96, 3.38, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube002.geometry}
        material={gltf.materials.billboards}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube002_1.geometry}
        material={gltf.materials['pr 1.001']}
      />
    </T.Group>
    <T.Group scale={329.69}>
      <T.Mesh
        geometry={gltf.nodes.Plane010.geometry}
        material={gltf.materials['grass floor']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_1.geometry}
        material={gltf.materials.floor}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_2.geometry}
        material={gltf.materials.street}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_3.geometry}
        material={gltf.materials.car}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_4.geometry}
        material={gltf.materials['dress red']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_5.geometry}
        material={gltf.materials.ram}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_6.geometry}
        material={gltf.materials['blue tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_7.geometry}
        material={gltf.materials['center flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_8.geometry}
        material={gltf.materials['leafs flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_9.geometry}
        material={gltf.materials['roots flower']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_10.geometry}
        material={gltf.materials.grass}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_11.geometry}
        material={gltf.materials.rock}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_12.geometry}
        material={gltf.materials.billboards}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_13.geometry}
        material={gltf.nodes.Plane010_13.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_14.geometry}
        material={gltf.materials['dark billboard']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_15.geometry}
        material={gltf.materials['ligth sine']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_16.geometry}
        material={gltf.materials['bottom tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_17.geometry}
        material={gltf.materials['dark blue ']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_18.geometry}
        material={gltf.materials['leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_19.geometry}
        material={gltf.materials['dark leafes tree']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_20.geometry}
        material={gltf.materials.text}
      />
    </T.Group>
    <T.Group
      position={[20, 0.01, -86]}
      scale={[0.5, 0.7, 0.29]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube008.geometry}
        material={gltf.materials.shoes}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_1.geometry}
        material={gltf.materials.skin}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_2.geometry}
        material={gltf.materials['shirt blue']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_3.geometry}
        material={gltf.materials['dress red']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_4.geometry}
        material={gltf.materials.jeans}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_5.geometry}
        material={gltf.materials.hair}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_6.geometry}
        material={gltf.materials.belt}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_7.geometry}
        material={gltf.materials.eyes}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
