<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\retro_computer.glb
Author: Tobalation (https://sketchfab.com/tobalation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-3a496376915846459d77fc14fdd6c1e0
Title: Retro computer
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('3dmodels/retro_computer.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      rotation={[-Math.PI / 2, 0, 0]}
      position={[1.55,0,0]}
      scale={6}
    >
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Object_4.geometry}
          material={gltf.materials.TextureGrid}
          position={[0, 0, -0.03]}
          rotation={[0.09, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_6.geometry}
          material={gltf.materials.TextureGrid}
          position={[0, 0.5, 0.03]}
          rotation={[0.09, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_8.geometry}
          material={gltf.materials.TextureGrid}
          position={[0.88, 0.06, 0.75]}
          rotation={[0.09, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.Object_10.geometry}
          material={gltf.materials.TextureGrid}
          position={[0, 0.06, 0.81]}
          rotation={[0.09, 0, 0]}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
