<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 .\PixelWorld.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, interactivity, HTML} from '@threlte/extras'
	import gsap from 'gsap';
  import { Spring } from 'svelte/motion'
  import { writable } from 'svelte/store'
  let { fallback, error, children, ref = $bindable(), object3D = $bindable(), ...props } = $props()

  const gltf = useGltf('3dmodels/PixelWorld.glb')


  interactivity()
  const scale = new Spring(1)
  
  let show = $state(false)

  let html = $state()

  $effect(() => {
    html.render()
  })

    const url = "https://en.wikipedia.org/wiki/Ilia_Topuria"

    import { Vector3 } from 'three'
    
  
  
  const characterInstance = writable()
  const moveDistance = writable(3)
  const jumpHeight = writable(1)
  let isMoving = $state(false)
  const moveduration = writable(0.2)

  /**
   * @param {import('three').Vector3} targetpostion
   * @param {number} targetrotation
   */
  function moveCharacter(targetpostion, targetrotation) {
    isMoving = true

    const timeline1 = gsap.timeline({
      onComplete () {
        isMoving = false
      }
    })

    timeline1.to($characterInstance.position,
    {
      x: targetpostion.x,
      z: targetpostion.z,
      duration: $moveduration,
    });
    timeline1.to($characterInstance.rotation,
    {
      y: targetrotation,
      duration: $moveduration,
    }, 
    0
  );

  timeline1.to($characterInstance.position,
    {
      y: $characterInstance.position.y + $jumpHeight,
      duration: $moveduration / 2,
      yoyo: true,
      repeat: 1,
    }, 
    0
  );
    
  }

/**
 * @param {KeyboardEvent} event
 */
  function onkeyDown(event) {
    if(isMoving) return;

  
    const targetposition = new Vector3().copy($characterInstance.position)
    let targetrotation = 0;
    

      switch (event.key.toLowerCase()) {
    case "w":
    case "arrowup":
      targetposition.x -= $moveDistance
      targetrotation = 0
      break

    case "s":
    case "arrowdown":
      targetposition.x += $moveDistance
      targetrotation = Math.PI
      break

    case "a":
    case "arrowleft":
      targetposition.z += $moveDistance
      targetrotation = Math.PI / 2
      break

    case "d":
    case "arrowright":
      targetposition.z -= $moveDistance
      targetrotation = -Math.PI / 2
      break
  }

  moveCharacter(targetposition, targetrotation)
}

  window.addEventListener("keydown", onkeyDown)
</script>

{#if show}
  <HTML
      position.y={20}
    autoRender={true}
    bind:this={html}
          position={[1, 7.46, -71]}


  >
    <div class="phone-wrapper" style="border-radius:1rem">
      <iframe
        title=""
        src={url}
        width="100%"
        height="100%"
        frameborder="0"
        >
      </iframe>
    </div>
  </HTML>
{/if}



<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[1, 7.46, -71]}
      rotation={[0, Math.PI / 2, 0]}
      scale={[4.96, 3.38, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube024.geometry}
        material={gltf.materials.billboards}
        scale={scale.current}
        onpointerenter={() => {
          scale.target = 1.2
          document.body.style.cursor = 'pointer'
        }}
        onpointerleave={() => {
          scale.target = 1
          document.body.style.cursor = 'auto'
        }}     
        onclick={() => {
          show = !show
        }} 
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube024_1.geometry}
        material={gltf.materials['pr 1']}
        castShadow
        receiveShadow
      />
    </T.Group>
    <T.Group
      position={[37.69, 6.62, 9.1]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[4.96, 3.38, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube001.geometry}
        material={gltf.materials.billboards}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_1.geometry}
        material={gltf.materials['pr 1.002']}
        castShadow
        receiveShadow
      />
    </T.Group>
    <T.Group
      position={[-72.58, 6.62, 26.72]}
      rotation={[0, Math.PI / 2, 0]}
      scale={[4.96, 3.38, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube002.geometry}
        material={gltf.materials.billboards}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube002_1.geometry}
        material={gltf.materials['pr 1.001']}
        castShadow
        receiveShadow
      />
    </T.Group>
    <T.Group scale={329.69}>
      <T.Mesh
        geometry={gltf.nodes.Plane010.geometry}
        material={gltf.materials['grass floor']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_1.geometry}
        material={gltf.materials.floor}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_2.geometry}
        material={gltf.materials.street}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_3.geometry}
        material={gltf.materials.car}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_4.geometry}
        material={gltf.materials['dress red']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_5.geometry}
        material={gltf.materials.ram}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_6.geometry}
        material={gltf.materials['blue tree']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_7.geometry}
        material={gltf.materials['center flower']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_8.geometry}
        material={gltf.materials['leafs flower']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_9.geometry}
        material={gltf.materials['roots flower']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_10.geometry}
        material={gltf.materials.grass}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_11.geometry}
        material={gltf.materials.rock}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_12.geometry}
        material={gltf.materials.billboards}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_13.geometry}
        material={gltf.nodes.Plane010_13.material}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_14.geometry}
        material={gltf.materials['dark billboard']}
        castShadow
        receiveShadow
      />

      <T.Mesh
        geometry={gltf.nodes.Plane010_15.geometry}
        material={gltf.materials['ligth sine']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_16.geometry}
        material={gltf.materials['bottom tree']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_17.geometry}
        material={gltf.materials['dark blue ']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_18.geometry}
        material={gltf.materials['leafes tree']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_19.geometry}
        material={gltf.materials['dark leafes tree']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Plane010_20.geometry}
        material={gltf.materials.text}
        castShadow
        receiveShadow
      />
    </T.Group>
    <!-- character -->
    <T.Group
      position={[20, 0.01, -86]}
      scale={[0.5, 0.7, 0.29]}
      bind:ref={$characterInstance}
      >
      <T.Mesh
        geometry={gltf.nodes.Cube008.geometry}
        material={gltf.materials.shoes}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_1.geometry}
        material={gltf.materials.skin}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_2.geometry}
        material={gltf.materials['shirt blue']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_3.geometry}
        material={gltf.materials['dress red']}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_4.geometry}
        material={gltf.materials.jeans}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_5.geometry}
        material={gltf.materials.hair}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_6.geometry}
        material={gltf.materials.belt}
        castShadow
        receiveShadow
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_7.geometry}
        material={gltf.materials.eyes}
        castShadow
        receiveShadow
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>


<style>
  .phone-wrapper {
    height: 200px;
    width: 420px;
    border-radius: 63px;
    overflow: hidden;
    border: 1px solid rgba(0, 0, 0, 0.1);
  }
</style>